version: "3.5"
services:
  postgres:
    container_name: reactive-db
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
  pgadmin:
    container_name: reactive-db-console
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
